package isis4208.tarea_2

import isis4208.FileSolver
import java.io.File
import java.util.*

// =================================================================
//                        Algorithm: Edmonds-Karp
// =================================================================

/**
 * Actual algorithm
 * In:
 * -  N: Int                        -> Number of nodes in the graph
 * -  capacities: Array<IntArray>   -> Capacities matrix capacities[i][j] = capacity from i to j
 * Out: MaxFlowResult               -> Aggregated object, solution for this problem: max capacity
 *
 * Explanation:
 * Let s (source = 0) and t (sink = N-1) be nodes of the input graph and c(u, v) (capacities) be the representation
 * of capacities from u to v, this algorithm calculates the maximum flow from s to t.
 *
 * 1. A residual graph (represented as matrix) is generated by cloning capacities and maxFlow = 0 as well.
 * 2. bfs is defined to find a path between vertices. For this, parent vertex is saved in parent array.
 *  (e.g. parent[u] = v means v -> u was found)
 * 3. While there is a path P from s to t in residual graph G_f, calculate though that path:
 *  - [First loop] from sink t to source s: compute pathBottleneck starting in MAX_VALUE:
 *      pathBottleneck = min_{(u,v) in P} residual[u][v]
 *  - [Second loop] from sink t to source s: updating the residual graph by updating the edges as follows:
 *      residual[u][v] - pathBottleneck
 *      residual[v][u] + pathBottleneck
 *
 *  - Update total flow value maxFlow = maxFlow + pathBottleneck
 *
 * 4. After repeating the previous steps for any possible path (until no path is found),
 *    assume max flow for all the graph is found, so returns the graph capacities - residual capacities as the max flow
 *    and the max flow value
 */
fun edmondsKarp(N: Int, capacities: Array<IntArray>): MaxFlowResult {
    val residual = Array(N) { i -> capacities[i].clone()}
    var maxFlow = 0

    // Source s, sink t
    val s = 0
    val t = N-1
    val parent = IntArray(N)

    fun bfs(): Boolean {
        //  Visited array, also path saver (reading from N-1 to 0)
        //  parent[u] = -1  -> not visited
        //  parent[u] = -2  -> node without source
        Arrays.fill(parent, -1)
        parent[s] = -2

        val queue: Queue<Int> = LinkedList()
        queue.add(s)

        while (queue.isNotEmpty()) {
            val u = queue.remove()
            for (v in 0 until N) {
                if (parent[v] == -1 && residual[u][v] > 0) {
                    parent[v] = u
                    if (v == t) return true
                    queue.add(v)
                }
            }
        }
        return false
    }

    while (bfs()) {
        var pathBottleneck = Int.MAX_VALUE

        var v = t
        while (v != s) {
            val u = parent[v]
            pathBottleneck = minOf(pathBottleneck, residual[u][v])
            v = u
        }

        v = t
        while (v != s) {
            val u = parent[v]
            residual[u][v] -= pathBottleneck
            residual[v][u] += pathBottleneck
            v = u
        }
        maxFlow += pathBottleneck
    }

    val flow = Array(N) { IntArray(N) }
    for (u in 0 until N) {
        for (v in 0 until N) {
            if (capacities[u][v] > 0) {
                flow[u][v] = capacities[u][v] - residual[u][v]
            }
        }
    }

    return MaxFlowResult(maxFlow, flow)
}

// =================================================================
//                  Problem Solver
// =================================================================

class EdmondsKarpSolver : FileSolver {

    private var N = 0
    private var capacities: Array<IntArray> = arrayOf()

    override fun solve(inputFile: File, outputPath: String?): String {
        val loadResults = loadCapacitiesFromFile(inputFile)
        N = loadResults.first
        capacities = loadResults.second

        val start = System.nanoTime()
        val maxFlow = edmondsKarp(N, capacities)
        val elapsedMs = (System.nanoTime() - start) / 1_000_000.0
        val outFile = writeMaxFlowOutput(inputFile, elapsedMs, maxFlow, outputPath, N, capacities)

        return buildString {
            appendLine("MaxFlow: ${maxFlow.maxFlow}")
            appendLine("Execution time: ${"%.3f".format(elapsedMs)} ms")
            appendLine("Output written to: ${outFile.path}")
        }
    }
}
